name: For each PR
on:
  pull_request:
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    name: E2E tests
    strategy:
      matrix:
        mode: ["arp", "rt", "bgp"]
      fail-fast: true
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      - name: Ensure fs wont cause issues
        run: sudo sysctl fs.inotify.max_user_instances=8192 &&  sudo sysctl fs.inotify.max_user_watches=524288
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Build image locally
        run: make dockerx86Local
      - name: Run Manifest generation tests
        run: make manifest-test
      - name: Run ARP mode tests v1.29.0 onwards
        run: E2E_KEEP_LOGS=true make e2e-tests129-arp
        if: matrix.mode== 'arp'
      - name: Run RT mode tests v1.29.0 onwards
        run: E2E_KEEP_LOGS=true make e2e-tests129-rt
        if: matrix.mode== 'rt'
      - name: Get GoBGP binaries
        run: make get-gobgp
        if: matrix.mode== 'bgp'
      - name: Run BGP mode tests v1.29.0 onwards
        run: sudo -E PATH=$PATH DOCKER_API_VERSION=1.48 E2E_KEEP_LOGS=true make e2e-tests129-bgp
        if: matrix.mode== 'bgp'
      - name: Change log directory permissions
        run: sudo chmod -R 755 /tmp/kube-vip-test-${{ matrix.mode }}*
        if: matrix.mode== 'bgp' && always()
      - name: Save logs
        uses: actions/upload-artifact@v6
        with:
          name: e2e-test-logs-${{ matrix.mode }}-${{ steps.date.outputs.date }}
          path: /tmp/kube-vip-test-${{ matrix.mode }}*
        if: always()
  service-e2e-tests:
    runs-on: ubuntu-latest
    name: E2E service tests
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Build image with iptables
        run: make dockerx86ActionIPTables
      - name: Run tests
        run: DOCKERTAG=action E2E_KEEP_LOGS=true make service-tests
      - name: Save logs
        uses: actions/upload-artifact@v6
        with:
          name: services-test-logs-${{ steps.date.outputs.date }}
          path: /tmp/kube-vip-service-tests*
        if: always()
